name: Deploy AgroVision ITM1 CI/CD
on:
  push:
    branches:
          -main   
build_and_deploy:
runs-on: ubuntu-latest 
  steps:
  name: 1. Checkout del Código
uses: actions/checkout@v3 
  name: 2. Configurar Variables de Entorno y Secrets
  run: |
    echo "BACKEND_PORT=9101" >> .env
    echo "FRONTEND_PORT=9401" >> .envGIT
    echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env    
  - name: 3. Construir y Levantar Contenedores (Despliegue)
  run: |
    docker-compose down 
    docker-compose up --build -d 
    - name: 4. Verificar API de Salud (/health)
  run: |
  sleep 5 
    curl http://localhost:9101/health      
- name: 5. Mensaje de Éxito
  run: echo "✅ Servicio AgroVision ITM1 desplegado. ¡Éxito en el CI/CD!"
      